USE triliogallery;
DELETE FROM photos;
INSERT INTO photos (title, caption, filename, size_bytes) VALUES ('Application Recovery', '', 'blog-01-application-recovery.jpg', 163267) ON DUPLICATE KEY UPDATE size_bytes=VALUES(size_bytes), title=VALUES(title);
INSERT INTO photos (title, caption, filename, size_bytes) VALUES ('Oracle Kubernetes Engine Backup', '', 'blog-02-oracle-kubernetes-engine-backup.jpg', 218506) ON DUPLICATE KEY UPDATE size_bytes=VALUES(size_bytes), title=VALUES(title);
INSERT INTO photos (title, caption, filename, size_bytes) VALUES ('Granular Recovery Tech', '', 'blog-03-granular-recovery-tech.jpg', 240022) ON DUPLICATE KEY UPDATE size_bytes=VALUES(size_bytes), title=VALUES(title);
INSERT INTO photos (title, caption, filename, size_bytes) VALUES ('Changed Block Tracking', '', 'blog-04-changed-block-tracking.jpg', 188475) ON DUPLICATE KEY UPDATE size_bytes=VALUES(size_bytes), title=VALUES(title);
INSERT INTO photos (title, caption, filename, size_bytes) VALUES ('Redis Backup Strategies', '', 'blog-05-redis-backup-strategies.jpg', 179800) ON DUPLICATE KEY UPDATE size_bytes=VALUES(size_bytes), title=VALUES(title);
INSERT INTO photos (title, caption, filename, size_bytes) VALUES ('Kubernetes PVC Backup', '', 'blog-06-kubernetes-pvc-backup.jpg', 179432) ON DUPLICATE KEY UPDATE size_bytes=VALUES(size_bytes), title=VALUES(title);
INSERT INTO photos (title, caption, filename, size_bytes) VALUES ('Proxmox Vs Openstack', '', 'blog-07-proxmox-vs-openstack.jpg', 220324) ON DUPLICATE KEY UPDATE size_bytes=VALUES(size_bytes), title=VALUES(title);
INSERT INTO photos (title, caption, filename, size_bytes) VALUES ('Snapshot Vs Backup', '', 'blog-08-snapshot-vs-backup.jpg', 216635) ON DUPLICATE KEY UPDATE size_bytes=VALUES(size_bytes), title=VALUES(title);
INSERT INTO photos (title, caption, filename, size_bytes) VALUES ('Red Hat Openshift On Azure', '', 'blog-09-red-hat-openshift-on-azure.jpg', 195184) ON DUPLICATE KEY UPDATE size_bytes=VALUES(size_bytes), title=VALUES(title);
INSERT INTO photos (title, caption, filename, size_bytes) VALUES ('Test Backup Recoverability', '', 'blog-10-test-backup-recoverability.jpg', 98634) ON DUPLICATE KEY UPDATE size_bytes=VALUES(size_bytes), title=VALUES(title);
INSERT INTO photos (title, caption, filename, size_bytes) VALUES ('Data Resiliency', '', 'blog-11-data-resiliency.jpg', 222190) ON DUPLICATE KEY UPDATE size_bytes=VALUES(size_bytes), title=VALUES(title);
INSERT INTO photos (title, caption, filename, size_bytes) VALUES ('How to Protect Your Data', '', 'blog-12-how-to-protect-your-data.jpg', 231519) ON DUPLICATE KEY UPDATE size_bytes=VALUES(size_bytes), title=VALUES(title);
