apiVersion: v1
kind: ConfigMap
metadata:
  name: gallery-sql
  namespace: trilio-demo
data:
  schema.sql: |
    
    CREATE DATABASE IF NOT EXISTS triliogallery;
    USE triliogallery;
    CREATE TABLE IF NOT EXISTS photos (
      id INT AUTO_INCREMENT PRIMARY KEY,
      title VARCHAR(120) NOT NULL,
      caption VARCHAR(240) DEFAULT NULL,
      filename VARCHAR(255) NOT NULL,
      size_bytes BIGINT DEFAULT 0,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

  seed.sql: |
    
    USE triliogallery;
    INSERT INTO photos (title, caption, filename, size_bytes) VALUES
    ('Application Recovery', 'Build & Execute Reliable Strategy', 'seed-1.svg', 2048),
    ('K8s Protection', 'Backup best practices', 'seed-2.svg', 2048),
    ('Cross-Cloud Restore', 'Mobility simplified', 'seed-3.svg', 2048);
