
CREATE DATABASE IF NOT EXISTS triliogallery;
USE triliogallery;
CREATE TABLE IF NOT EXISTS photos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(120) NOT NULL,
  caption VARCHAR(240) DEFAULT NULL,
  filename VARCHAR(255) NOT NULL,
  size_bytes BIGINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
